### ISSUE TITLE
Centralização dos textos nas tabelas

### ISSUE THREAD

**Issue by thiagoalencar** [UnB-CIC/Monografia#12]
Os textos dentro de cada célula não ficam alinhando quando usa-se os tipos de coluna p, m ou b.
Pode-se criar uma novo tipo de coluna com o package array.
% Cria dois novos tipos de coluna do tipo parágrafo. P paratexto centraliado horizontalmente na célula. M para texto centralizado verticalmente na célula.
\RequirePackage{array}
\newcolumntype{P}[1]{>{\centering\arraybackslash}p{#1}}
\newcolumntype{M}[1]{>{\centering\arraybackslash}m{#1}}

**Comment by gnramos** [comment]
Não é issue com a classe.
