### ISSUE TITLE
Alerta tocstyle: "Package tocstyle Warning: THIS IS AN ALPHA VERSION!"

### ISSUE THREAD

**Issue by heitorfaria** [UnB-CIC/Monografia#13]
Olá,

Proponho remédio para o seguinte alerta / uso de biblioteca:

>> "/usr/share/texlive/texmf-dist/tex/latex/koma-script/tocstyle.sty:
>> Package tocstyle Warning: THIS IS AN ALPHA VERSION!
>> (tocstyle)                USAGE OF THIS VERSION IS ON YOUR OWN RISK!
>> (tocstyle)                EVERYTHING MAY HAPPEN!
>> (tocstyle)                EVERYTHING MAY CHANGE IN FUTURE!
>> (tocstyle)                THERE IS NO SUPPORT, IF YOU USE THIS PACKAGE!
>> (tocstyle)                Maybe it would be better, not to load this
>> package."

Alterar linha 187 do .cls: 

%\usepackage[tocindentauto]{tocstyle}% Indentação de anexos na TOC
%\usetocstyle{standard}%
\usepackage[titles]{tocloft}

**Comment by gnramos** [comment]
Sugestão de melhoria. Not broken, won't fix.
