### ISSUE TITLE
Itálico nos títulos.

### ISSUE THREAD

**Issue by tiagoalves83** [UnB-CIC/Monografia#14]
Nenhuma das duas formas funciona.

/title{Blaa Bla Bla \textit{Blabla} Bla}

/title{Blaa Bla Bla {\it Blabla} Bla}

**Comment by waldeyr** [comment]
Alguma solução? 
Também já usei \protect sem sucesso.

**Comment by waldeyr** [comment]
Dica do Daniel Saad:

Sunstituir o código:  (gdef por xdef)

```
\newcommand{\set@title}[2][]{
	\gdef\@title{#1}
	\gdef\@maintitle{#2}
}
```
Depois usar no título:

` \titulo{ {\it Palavra} }`

**Comment by gnramos** [comment]
Sugestão de alteração de estilo. Subjetivo, deve ser encaminhada em Colegiado.
