### ISSUE TITLE
Modelo falta padrão ABNT de citação direta

### ISSUE THREAD

**Issue by Skalwalker** [UnB-CIC/Monografia#19]
Modelo não possui comando para citação com nomes de autores. Exemplo:

Segundo Vaz (2008, p. 63) “não saber usar a internet em um futuro próximo será como não saber abrir um livro ou acender um fogão, não sabermos algo que nos permita viver a cidadania na sua completitude”.

Sugere-se implementação dessa possibilidade de citação. 
###

**Comment by gnramos** [comment]
O modelo não segue o padrão ABNT.
