### ISSUE TITLE
Pacote "tocstyle" está abandonado

### ISSUE THREAD

**Issue by JPTIZ** [UnB-CIC/Monografia#20]
Como o [tocstyle foi abandonado](https://ctan.math.washington.edu/tex-archive/obsolete/macros/latex/contrib/koma-script-obsolete/tocstyle-obsolete.pdf):

> _"Since KOMA-Script 3.31 the package has been removed from
> KOMA-Script. It is deprecated and should not be used any
> longer."_

O projeto não é mais compilável nas versões mais recentes de distribuições LaTeX (como TeXLive 2021). Uma sugestão é passar a utilizar a [tocbasic](https://ctan.org/pkg/tocbasic?lang=en).

**Comment by streeg** [comment]
Mesmo erro em 2022. Contornei seguindo a solução acima.
