### ISSUE TITLE
Tradução de termos da bibliografia.

### ISSUE THREAD

**Issue by gnramos** [UnB-CIC/Monografia#4]
Alguns termos não são traduzidos para Português. Exemplos:
- @inproceedings: "In" <nome dos anais>
- @inproceedings: "pages" <# das páginas>
- @book: "editor" <nome do editor>
- @inproceedings: "sept" (nome do mês)
- @article: "April" (nome do mês)
- @incollection: <conteúdo de "note", se houver>

**Comment by TomazAlexandre** [comment]
ok
